# golangci-lint configuration file
version: "2"

linters:
  enable:
    - govet
    - ineffassign
    - misspell
    - unused
    - staticcheck
    - errcheck
  disable:
    - gosec # Disable for now due to dependency issues
  settings:
    misspell:
      locale: US
      ignore-rules:
        - colour
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly